name: Build and deploy Hugo site to gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.0'
          extended: true

      - name: Build site
        env:
          HUGO_ENV: production
        run: |
          hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          # Use the GITHUB_TOKEN provided by Actions - no extra secret required
          github_token: ${{ secrets.GITHUB_TOKEN }}
